//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34003
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCResourceManager.ResourceFilter.ResourceFilter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCResourceManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   抽出しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_btnToCommon_Click_抽出しました {
            get {
                return ResourceManager.GetString("FormMain_btnToCommon_Click_抽出しました", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リソースファイルを上書きしてよろしいですか？（バックアップは作ります) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_btnToRes_Click_ {
            get {
                return ResourceManager.GetString("FormMain_btnToRes_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rcファイルを書き換えました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_btnToRes_Click_rcファイルを書き換えました {
            get {
                return ResourceManager.GetString("FormMain_btnToRes_Click_rcファイルを書き換えました", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共通領域のリソースファイルが一つも選択されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_btnToRes_Click_共通領域のリソースファイルが一つも選択されていません {
            get {
                return ResourceManager.GetString("FormMain_btnToRes_Click_共通領域のリソースファイルが一つも選択されていません", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_btnToRes_Click_警告 {
            get {
                return ResourceManager.GetString("FormMain_btnToRes_Click_警告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共通領域のリソースファイルが一つも選択されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_btnToResAdd_Click_共通領域のリソースファイルが一つも選択されていません {
            get {
                return ResourceManager.GetString("FormMain_btnToResAdd_Click_共通領域のリソースファイルが一つも選択されていません", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップファイルが存在しないのでチェックできません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_chkShowDiffrence_CheckedChanged_バックアップファイルが存在しないのでチェックできません {
            get {
                return ResourceManager.GetString("FormMain_chkShowDiffrence_CheckedChanged_バックアップファイルが存在しないのでチェックできません", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RCファイルがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_LoadFromResource_RCファイルがありません {
            get {
                return ResourceManager.GetString("FormMain_LoadFromResource_RCファイルがありません", resourceCulture);
            }
        }
        
        /// <summary>
        ///   resman file|*.resman に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormMain_toolStripMenuItem2_Click_resman_file___resman {
            get {
                return ResourceManager.GetString("FormMain_toolStripMenuItem2_Click_resman_file___resman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   data folder|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FromSettings_btnRefDataFolder_Click_data_folder____ {
            get {
                return ResourceManager.GetString("FromSettings_btnRefDataFolder_Click_data_folder____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rc file|*.rc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FromSettings_btnRefRcPath_Click_rc_file___rc {
            get {
                return ResourceManager.GetString("FromSettings_btnRefRcPath_Click_rc_file___rc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   resource.h|*.h に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FromSettings_btnRefResourceHPath_Click_resource_h___h {
            get {
                return ResourceManager.GetString("FromSettings_btnRefResourceHPath_Click_resource_h___h", resourceCulture);
            }
        }
    }
}
